"""PLX Technology (0x10B5) PCIe switch IC definitions.

Data sources:
- Broadcom product pages
- Linux PCI ID database (https://pci-ids.ucw.cz/)
- Observed hardware

PLX was acquired by Avago (2014), which merged with Broadcom (2016).
Gen1-Gen3 switches use the original PLX vendor ID 0x10B5.
"""

from plxtools.switchdb._vendors import PLX_VENDOR_ID
from plxtools.switchdb.models import PCIeGen, SwitchIC

# =============================================================================
# PEX8500 Family - Gen1 (2.5 GT/s)
# =============================================================================

PEX8500_FAMILY: list[SwitchIC] = [
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8508,
        part_number="PEX8508",
        description="8-lane, 5-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=8,
        max_ports=5,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8509,
        part_number="PEX8509",
        description="8-lane, 9-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=8,
        max_ports=9,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8512,
        part_number="PEX8512",
        description="12-lane, 5-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=12,
        max_ports=5,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8516,
        part_number="PEX8516",
        description="16-lane, 4-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=16,
        max_ports=4,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8517,
        part_number="PEX8517",
        description="16-lane, 5-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=16,
        max_ports=5,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8518,
        part_number="PEX8518",
        description="16-lane, 5-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=16,
        max_ports=5,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8524,
        part_number="PEX8524",
        description="24-lane, 6-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=24,
        max_ports=6,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8525,
        part_number="PEX8525",
        description="24-lane, 5-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=24,
        max_ports=5,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8532,
        part_number="PEX8532",
        description="32-lane, 10-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=32,
        max_ports=10,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8533,
        part_number="PEX8533",
        description="32-lane, 6-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=32,
        max_ports=6,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8547,
        part_number="PEX8547",
        description="48-lane, 3-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=48,
        max_ports=3,
        family="PEX8500",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8548,
        part_number="PEX8548",
        description="48-lane, 9-port PCIe Gen1 switch",
        pcie_gen=PCIeGen.GEN1,
        total_lanes=48,
        max_ports=9,
        family="PEX8500",
    ),
]

# =============================================================================
# PEX8600 Family - Gen2 (5.0 GT/s)
# =============================================================================

PEX8600_FAMILY: list[SwitchIC] = [
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8603,
        part_number="PEX8603",
        description="3-lane, 3-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=3,
        max_ports=3,
        max_port_width=1,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8604,
        part_number="PEX8604",
        description="4-lane, 4-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=4,
        max_ports=4,
        max_port_width=1,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8605,
        part_number="PEX8605",
        description="4-lane, 4-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=4,
        max_ports=4,
        max_port_width=1,
        family="PEX8600",
        has_dma=False,
        notes="Common in budget NVMe cards",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8606,
        part_number="PEX8606",
        description="6-lane, 6-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=6,
        max_ports=6,
        max_port_width=2,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8608,
        part_number="PEX8608",
        description="8-lane, 8-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=8,
        max_ports=8,
        max_port_width=1,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8609,
        part_number="PEX8609",
        description="8-lane, 8-port PCIe Gen2 switch with DMA",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=8,
        max_ports=8,
        max_port_width=4,
        family="PEX8600",
        has_dma=True,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8612,
        part_number="PEX8612",
        description="12-lane, 3-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=12,
        max_ports=3,
        max_port_width=4,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8613,
        part_number="PEX8613",
        description="12-lane, 4-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=12,
        max_ports=4,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8614,
        part_number="PEX8614",
        description="12-lane, 12-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=12,
        max_ports=12,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8615,
        part_number="PEX8615",
        description="12-lane, 3-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=12,
        max_ports=3,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8616,
        part_number="PEX8616",
        description="16-lane, 4-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=16,
        max_ports=4,
        max_port_width=4,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8617,
        part_number="PEX8617",
        description="16-lane, 4-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=16,
        max_ports=4,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8618,
        part_number="PEX8618",
        description="16-lane, 16-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=16,
        max_ports=16,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8619,
        part_number="PEX8619",
        description="16-lane, 16-port PCIe Gen2 switch with DMA",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=16,
        max_ports=16,
        max_port_width=4,
        family="PEX8600",
        has_dma=True,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8624,
        part_number="PEX8624",
        description="24-lane, 6-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=24,
        max_ports=6,
        max_port_width=4,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8625,
        part_number="PEX8625",
        description="24-lane, 24-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=24,
        max_ports=24,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8632,
        part_number="PEX8632",
        description="32-lane, 12-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=32,
        max_ports=12,
        max_port_width=8,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8636,
        part_number="PEX8636",
        description="36-lane, 12-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=36,
        max_ports=12,
        max_port_width=8,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8647,
        part_number="PEX8647",
        description="48-lane, 3-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=48,
        max_ports=3,
        family="PEX8600",
        has_dma=False,
        package="27x27mm FCBGA",
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8647",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8648,
        part_number="PEX8648",
        description="48-lane, 12-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=48,
        max_ports=12,
        max_port_width=8,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8649,
        part_number="PEX8649",
        description="48-lane, 12-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=48,
        max_ports=12,
        max_port_width=8,
        family="PEX8600",
        has_dma=False,
        package="27x27mm FCBGA",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8680,
        part_number="PEX8680",
        description="80-lane, 20-port PCIe Gen2 switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=80,
        max_ports=20,
        max_port_width=16,
        family="PEX8600",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8696,
        part_number="PEX8696",
        description="96-lane, 24-port PCIe Gen2 Multi-Root switch",
        pcie_gen=PCIeGen.GEN2,
        total_lanes=96,
        max_ports=24,
        family="PEX8600",
        has_dma=False,
        has_nt=True,
        package="35x35mm FCBGA",
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8696",
    ),
]

# =============================================================================
# PEX8700 Family - Gen3 (8.0 GT/s)
# =============================================================================

PEX8700_FAMILY: list[SwitchIC] = [
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8712,
        part_number="PEX8712",
        description="12-lane, 3-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=12,
        max_ports=3,
        max_port_width=4,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8713,
        part_number="PEX8713",
        description="12-lane, 4-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=12,
        max_ports=4,
        max_port_width=4,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8714,
        part_number="PEX8714",
        description="12-lane, 5-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=12,
        max_ports=5,
        max_port_width=4,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8716,
        part_number="PEX8716",
        description="16-lane, 4-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=16,
        max_ports=4,
        max_port_width=4,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8717,
        part_number="PEX8717",
        description="16-lane, 8-port PCIe Gen3 switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=16,
        max_ports=8,
        max_port_width=8,
        family="PEX8700",
        has_dma=True,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8718,
        part_number="PEX8718",
        description="16-lane, 5-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=16,
        max_ports=5,
        max_port_width=8,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8723,
        part_number="PEX8723",
        description="24-lane, 6-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=24,
        max_ports=6,
        max_port_width=8,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8724,
        part_number="PEX8724",
        description="24-lane, 6-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=24,
        max_ports=6,
        family="PEX8700",
        has_dma=False,
        package="19x19mm FCBGA",
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8724",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8725,
        part_number="PEX8725",
        description="24-lane, 10-port PCIe Gen3 Multi-Root switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=24,
        max_ports=10,
        max_port_width=8,
        family="PEX8700",
        has_dma=True,
        has_nt=True,
        notes="4 DMA engines",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8732,
        part_number="PEX8732",
        description="32-lane, 8-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=32,
        max_ports=8,
        max_port_width=8,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8733,
        part_number="PEX8733",
        description="32-lane, 18-port PCIe Gen3 switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=32,
        max_ports=18,
        max_port_width=8,
        family="PEX8700",
        has_dma=True,
        has_nt=True,
        package="27x27mm FCBGA",
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8733",
        notes="Part of performancePAK family with PEX8749/8725. 4 DMA engines.",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8734,
        part_number="PEX8734",
        description="32-lane, 8-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=32,
        max_ports=8,
        max_port_width=8,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8747,
        part_number="PEX8747",
        description="48-lane, 5-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=48,
        max_ports=5,
        max_port_width=16,
        family="PEX8700",
        has_dma=False,
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8747",
        notes="Flexible x8/x16 lane allocation",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8748,
        part_number="PEX8748",
        description="48-lane, 12-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=48,
        max_ports=12,
        max_port_width=16,
        family="PEX8700",
        has_dma=False,
        package="27x27mm FCBGA",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8749,
        part_number="PEX8749",
        description="48-lane, 18-port PCIe Gen3 Multi-Root switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=48,
        max_ports=18,
        family="PEX8700",
        has_dma=True,
        has_nt=True,
        package="27x27mm FCBGA",
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8749",
        notes="4 DMA engines (Linux plx_dma driver). 2 NT ports, 2 VCs.",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8764,
        part_number="PEX8764",
        description="64-lane, 16-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=64,
        max_ports=16,
        max_port_width=16,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8780,
        part_number="PEX8780",
        description="80-lane, 20-port PCIe Gen3 switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=80,
        max_ports=20,
        max_port_width=16,
        family="PEX8700",
        has_dma=False,
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x8796,
        part_number="PEX8796",
        description="96-lane, 24-port PCIe Gen3 Multi-Root switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=96,
        max_ports=24,
        family="PEX8700",
        has_dma=True,
        has_nt=True,
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/pcie-switches/pex8796",
        notes="4 DMA engines, 2 NT ports, 2 VCs. performancePAK family.",
    ),
]

# =============================================================================
# PEX9700 Family - Gen3 ExpressFabric
# =============================================================================

PEX9700_FAMILY: list[SwitchIC] = [
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9712,
        part_number="PEX9712",
        description="12-lane, 4-port PCIe Gen3 ExpressFabric switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=12,
        max_ports=4,
        family="PEX9700",
        has_dma=True,
        notes="ExpressFabric platform with multi-host support",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9733,
        part_number="PEX9733",
        description="32-lane, 18-port PCIe Gen3 ExpressFabric switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=32,
        max_ports=18,
        family="PEX9700",
        has_dma=True,
        notes="ExpressFabric platform with multi-host support",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9749,
        part_number="PEX9749",
        description="48-lane, 18-port PCIe Gen3 ExpressFabric switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=48,
        max_ports=18,
        family="PEX9700",
        has_dma=True,
        notes="ExpressFabric platform with multi-host support",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9765,
        part_number="PEX9765",
        description="65-lane, 17-port PCIe Gen3 ExpressFabric switch with DMA",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=65,
        max_ports=17,
        family="PEX9700",
        has_dma=True,
        product_url="https://www.broadcom.com/products/pcie-switches-bridges/expressfabric/gen3/pex9765",
        notes="4 DMA engines. Multi-host capable.",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9781,
        part_number="PEX9781",
        description="81-lane, 17-port PCIe Gen3 ExpressFabric switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=81,
        max_ports=17,
        family="PEX9700",
        has_dma=True,
        notes="ExpressFabric platform",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x9797,
        part_number="PEX9797",
        description="97-lane, 25-port PCIe Gen3 ExpressFabric switch",
        pcie_gen=PCIeGen.GEN3,
        total_lanes=97,
        max_ports=25,
        family="PEX9700",
        has_dma=True,
        notes="ExpressFabric platform",
    ),
]

# =============================================================================
# Auxiliary/Virtual Devices
# These are secondary functions exposed by some switches (DMA, NT bridge, etc.)
# =============================================================================

PLX_AUX_DEVICES: list[SwitchIC] = [
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x87A0,
        part_number="PEX-NT-VEP",
        description="PLX Non-Transparent Bridge Virtual Endpoint",
        family="Auxiliary",
        notes="NT bridge endpoint exposed by multi-root switches",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x87B0,
        part_number="PEX-NT-LINK",
        description="PLX Non-Transparent Bridge Link Port",
        family="Auxiliary",
        notes="NT bridge link interface",
    ),
    SwitchIC(
        vendor_id=PLX_VENDOR_ID,
        device_id=0x87D0,
        part_number="PEX8749-DMA",
        description="PEX8749 DMA Controller Endpoint",
        family="Auxiliary",
        notes="DMA controller function exposed by PEX8749",
    ),
]

# =============================================================================
# Combined list of all PLX devices
# =============================================================================

PLX_DEVICES: list[SwitchIC] = (
    PEX8500_FAMILY
    + PEX8600_FAMILY
    + PEX8700_FAMILY
    + PEX9700_FAMILY
    + PLX_AUX_DEVICES
)
